/* eslint-disable max-len */
const swaggerAutogen = require('swagger-autogen')();
const path = require('path');
const outputFile = path.join(__dirname, './swagger/swagger_output.json');
const endpointsFiles = [path.join(__dirname, './api/sensor/router.js'),
    path.join(__dirname, './api/shortener/router.js')];

const doc = {
    info: {
        version: '1.0.0',
        title: 'Physical Web URL Shortener and Sensor Station',
        description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
    },
    host: 'breoteshr.ml',
    basePath: '/',
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            'name': 'Station',
            'description': 'Station registration system for enabling physical web',
        },
    ],
    definitions: {
        Station: {
            uuid: 'ec2f07a3-2463-440b-af7a-2df34068c788',
            webid: 'tentang',
            urlId: 'BqX',
            shortUrl: 'https://breoteshr.ml/BqX',
            longUrl: 'https://madejombang.id/tentang/',
            sensors: [
                {
                    id_sensor: 'SEN2PB',
                    type: 'DHT11',
                    value: 78,
                    valueUnit: 'Humidity',
                    displayUnit: '%',
                    minValue: '0',
                    maxValue: '100',
                },
                {
                    id_sensor: 'SEN187',
                    type: 'Smoke Sensor',
                    value: 50,
                    valueUnit: 'Smokiness',
                    displayUnit: '%',
                    minValue: '0',
                    maxValue: '100',
                },
            ],
        },
        Sensor: {
            id_sensor: 'SEN2PB',
            type: 'DHT11',
            value: 78,
            valueUnit: 'Humidity',
            displayUnit: '%',
            minValue: '0',
            maxValue: '100',
        },
    },


};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js');
});
